-- V1__init_schema.sql
-- Base schema definition for Charles Schwab Audit Log Service

CREATE TABLE audit_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequence_number BIGINT NOT NULL UNIQUE,
    event_type VARCHAR(255) NOT NULL,
    actor_id VARCHAR(255) NOT NULL,
    resource_type VARCHAR(255) NOT NULL,
    resource_id VARCHAR(255) NOT NULL,
    payload_json TEXT,
    redactions_json TEXT,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    previous_hash VARCHAR(64) NOT NULL,
    record_hash VARCHAR(64) NOT NULL,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    archived_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_actor ON audit_records (actor_id);
CREATE INDEX idx_resource ON audit_records (resource_type, resource_id);
CREATE INDEX idx_event_type ON audit_records (event_type);
CREATE INDEX idx_timestamp ON audit_records (timestamp);
