-- V2__add_checkpoints_and_idempotency.sql
-- External chain head checkpoints and idempotency replay protection schema

CREATE TABLE chain_checkpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkpoint_id VARCHAR(255) NOT NULL UNIQUE,
    head_sequence_number BIGINT NOT NULL,
    head_record_hash VARCHAR(64) NOT NULL,
    checkpoint_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    checkpoint_version VARCHAR(50) NOT NULL,
    signature VARCHAR(512) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'VALID'
);

CREATE INDEX idx_checkpoint_seq ON chain_checkpoints (head_sequence_number);
CREATE INDEX idx_checkpoint_time ON chain_checkpoints (checkpoint_timestamp);

CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    request_hash VARCHAR(64) NOT NULL,
    audit_record_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_idempotency_key ON idempotency_records (idempotency_key);
